/*
CE-RISE Hexagonal Core Service API

Testing ModelsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hexcoresdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_hexcoresdk_ModelsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ModelsAPIService CreateRecord", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var model string
		var version string

		resp, httpRes, err := apiClient.ModelsAPI.CreateRecord(context.Background(), model, version).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ModelsAPIService QueryRecords", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var model string
		var version string

		resp, httpRes, err := apiClient.ModelsAPI.QueryRecords(context.Background(), model, version).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ModelsAPIService ValidateModelPayload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var model string
		var version string

		resp, httpRes, err := apiClient.ModelsAPI.ValidateModelPayload(context.Background(), model, version).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
