/*
CE-RISE Hex Core Service API

Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

API version: 0.0.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hexcoresdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecordQueryFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordQueryFilter{}

// RecordQueryFilter Canonical backend query dialect shared across record store adapters.
type RecordQueryFilter struct {
	// AND-only list of query predicates.
	Where []RecordQueryCondition `json:"where"`
	// Optional list of sort directives applied in order.
	Sort []RecordQuerySort `json:"sort,omitempty"`
	// Maximum number of records to return.
	Limit *int64 `json:"limit,omitempty"`
	// Zero-based row offset for pagination.
	Offset *int64 `json:"offset,omitempty"`
}

type _RecordQueryFilter RecordQueryFilter

// NewRecordQueryFilter instantiates a new RecordQueryFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordQueryFilter(where []RecordQueryCondition) *RecordQueryFilter {
	this := RecordQueryFilter{}
	this.Where = where
	return &this
}

// NewRecordQueryFilterWithDefaults instantiates a new RecordQueryFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordQueryFilterWithDefaults() *RecordQueryFilter {
	this := RecordQueryFilter{}
	return &this
}

// GetWhere returns the Where field value
func (o *RecordQueryFilter) GetWhere() []RecordQueryCondition {
	if o == nil {
		var ret []RecordQueryCondition
		return ret
	}

	return o.Where
}

// GetWhereOk returns a tuple with the Where field value
// and a boolean to check if the value has been set.
func (o *RecordQueryFilter) GetWhereOk() ([]RecordQueryCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Where, true
}

// SetWhere sets field value
func (o *RecordQueryFilter) SetWhere(v []RecordQueryCondition) {
	o.Where = v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *RecordQueryFilter) GetSort() []RecordQuerySort {
	if o == nil || IsNil(o.Sort) {
		var ret []RecordQuerySort
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordQueryFilter) GetSortOk() ([]RecordQuerySort, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *RecordQueryFilter) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []RecordQuerySort and assigns it to the Sort field.
func (o *RecordQueryFilter) SetSort(v []RecordQuerySort) {
	o.Sort = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *RecordQueryFilter) GetLimit() int64 {
	if o == nil || IsNil(o.Limit) {
		var ret int64
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordQueryFilter) GetLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *RecordQueryFilter) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int64 and assigns it to the Limit field.
func (o *RecordQueryFilter) SetLimit(v int64) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *RecordQueryFilter) GetOffset() int64 {
	if o == nil || IsNil(o.Offset) {
		var ret int64
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordQueryFilter) GetOffsetOk() (*int64, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *RecordQueryFilter) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int64 and assigns it to the Offset field.
func (o *RecordQueryFilter) SetOffset(v int64) {
	o.Offset = &v
}

func (o RecordQueryFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordQueryFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["where"] = o.Where
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	return toSerialize, nil
}

func (o *RecordQueryFilter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"where",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordQueryFilter := _RecordQueryFilter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecordQueryFilter)

	if err != nil {
		return err
	}

	*o = RecordQueryFilter(varRecordQueryFilter)

	return err
}

type NullableRecordQueryFilter struct {
	value *RecordQueryFilter
	isSet bool
}

func (v NullableRecordQueryFilter) Get() *RecordQueryFilter {
	return v.value
}

func (v *NullableRecordQueryFilter) Set(val *RecordQueryFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordQueryFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordQueryFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordQueryFilter(val *RecordQueryFilter) *NullableRecordQueryFilter {
	return &NullableRecordQueryFilter{value: val, isSet: true}
}

func (v NullableRecordQueryFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordQueryFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


