/*
CE-RISE Hex Core Service API

Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

API version: 0.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hexcoresdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecordQuerySort type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordQuerySort{}

// RecordQuerySort struct for RecordQuerySort
type RecordQuerySort struct {
	// Sortable field path such as `created_at` or `payload.record_scope`.
	Field string `json:"field"`
	// Sort direction.
	Direction string `json:"direction"`
}

type _RecordQuerySort RecordQuerySort

// NewRecordQuerySort instantiates a new RecordQuerySort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordQuerySort(field string, direction string) *RecordQuerySort {
	this := RecordQuerySort{}
	this.Field = field
	this.Direction = direction
	return &this
}

// NewRecordQuerySortWithDefaults instantiates a new RecordQuerySort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordQuerySortWithDefaults() *RecordQuerySort {
	this := RecordQuerySort{}
	return &this
}

// GetField returns the Field field value
func (o *RecordQuerySort) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *RecordQuerySort) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *RecordQuerySort) SetField(v string) {
	o.Field = v
}

// GetDirection returns the Direction field value
func (o *RecordQuerySort) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *RecordQuerySort) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *RecordQuerySort) SetDirection(v string) {
	o.Direction = v
}

func (o RecordQuerySort) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordQuerySort) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["direction"] = o.Direction
	return toSerialize, nil
}

func (o *RecordQuerySort) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
		"direction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordQuerySort := _RecordQuerySort{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecordQuerySort)

	if err != nil {
		return err
	}

	*o = RecordQuerySort(varRecordQuerySort)

	return err
}

type NullableRecordQuerySort struct {
	value *RecordQuerySort
	isSet bool
}

func (v NullableRecordQuerySort) Get() *RecordQuerySort {
	return v.value
}

func (v *NullableRecordQuerySort) Set(val *RecordQuerySort) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordQuerySort) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordQuerySort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordQuerySort(val *RecordQuerySort) *NullableRecordQuerySort {
	return &NullableRecordQuerySort{value: val, isSet: true}
}

func (v NullableRecordQuerySort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordQuerySort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


