/*
CE-RISE Hex Core Service API

Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

API version: 0.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hexcoresdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRequest{}

// CreateRequest struct for CreateRequest
type CreateRequest struct {
	// Payload to validate and persist as a new record.
	Payload map[string]interface{} `json:"payload"`
}

type _CreateRequest CreateRequest

// NewCreateRequest instantiates a new CreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRequest(payload map[string]interface{}) *CreateRequest {
	this := CreateRequest{}
	this.Payload = payload
	return &this
}

// NewCreateRequestWithDefaults instantiates a new CreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRequestWithDefaults() *CreateRequest {
	this := CreateRequest{}
	return &this
}

// GetPayload returns the Payload field value
func (o *CreateRequest) GetPayload() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *CreateRequest) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// SetPayload sets field value
func (o *CreateRequest) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

func (o CreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["payload"] = o.Payload
	return toSerialize, nil
}

func (o *CreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"payload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRequest := _CreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRequest)

	if err != nil {
		return err
	}

	*o = CreateRequest(varCreateRequest)

	return err
}

type NullableCreateRequest struct {
	value *CreateRequest
	isSet bool
}

func (v NullableCreateRequest) Get() *CreateRequest {
	return v.value
}

func (v *NullableCreateRequest) Set(val *CreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRequest(val *CreateRequest) *NullableCreateRequest {
	return &NullableCreateRequest{value: val, isSet: true}
}

func (v NullableCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


