/*
CE-RISE Hex Core Service API

Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

API version: 0.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hexcoresdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecordQueryCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordQueryCondition{}

// RecordQueryCondition struct for RecordQueryCondition
type RecordQueryCondition struct {
	// Field path such as `id` or `payload.record_scope`.
	Field string `json:"field"`
	// Comparison operator.
	Op string `json:"op"`
	// Operand value. For `in` this must be an array. For `exists` this should be boolean.
	Value interface{} `json:"value"`
}

type _RecordQueryCondition RecordQueryCondition

// NewRecordQueryCondition instantiates a new RecordQueryCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordQueryCondition(field string, op string, value interface{}) *RecordQueryCondition {
	this := RecordQueryCondition{}
	this.Field = field
	this.Op = op
	this.Value = value
	return &this
}

// NewRecordQueryConditionWithDefaults instantiates a new RecordQueryCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordQueryConditionWithDefaults() *RecordQueryCondition {
	this := RecordQueryCondition{}
	return &this
}

// GetField returns the Field field value
func (o *RecordQueryCondition) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *RecordQueryCondition) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *RecordQueryCondition) SetField(v string) {
	o.Field = v
}

// GetOp returns the Op field value
func (o *RecordQueryCondition) GetOp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Op
}

// GetOpOk returns a tuple with the Op field value
// and a boolean to check if the value has been set.
func (o *RecordQueryCondition) GetOpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Op, true
}

// SetOp sets field value
func (o *RecordQueryCondition) SetOp(v string) {
	o.Op = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *RecordQueryCondition) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecordQueryCondition) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RecordQueryCondition) SetValue(v interface{}) {
	o.Value = v
}

func (o RecordQueryCondition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordQueryCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["op"] = o.Op
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

func (o *RecordQueryCondition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
		"op",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordQueryCondition := _RecordQueryCondition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecordQueryCondition)

	if err != nil {
		return err
	}

	*o = RecordQueryCondition(varRecordQueryCondition)

	return err
}

type NullableRecordQueryCondition struct {
	value *RecordQueryCondition
	isSet bool
}

func (v NullableRecordQueryCondition) Get() *RecordQueryCondition {
	return v.value
}

func (v *NullableRecordQueryCondition) Set(val *RecordQueryCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordQueryCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordQueryCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordQueryCondition(val *RecordQueryCondition) *NullableRecordQueryCondition {
	return &NullableRecordQueryCondition{value: val, isSet: true}
}

func (v NullableRecordQueryCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordQueryCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


