/*
CE-RISE Hex Core Service API

Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

API version: 0.0.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hexcoresdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidationReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationReport{}

// ValidationReport struct for ValidationReport
type ValidationReport struct {
	// True when no blocking validation issues were found.
	Passed bool `json:"passed"`
	Results []ValidationResult `json:"results"`
}

type _ValidationReport ValidationReport

// NewValidationReport instantiates a new ValidationReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationReport(passed bool, results []ValidationResult) *ValidationReport {
	this := ValidationReport{}
	this.Passed = passed
	this.Results = results
	return &this
}

// NewValidationReportWithDefaults instantiates a new ValidationReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationReportWithDefaults() *ValidationReport {
	this := ValidationReport{}
	return &this
}

// GetPassed returns the Passed field value
func (o *ValidationReport) GetPassed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Passed
}

// GetPassedOk returns a tuple with the Passed field value
// and a boolean to check if the value has been set.
func (o *ValidationReport) GetPassedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Passed, true
}

// SetPassed sets field value
func (o *ValidationReport) SetPassed(v bool) {
	o.Passed = v
}

// GetResults returns the Results field value
func (o *ValidationReport) GetResults() []ValidationResult {
	if o == nil {
		var ret []ValidationResult
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *ValidationReport) GetResultsOk() ([]ValidationResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *ValidationReport) SetResults(v []ValidationResult) {
	o.Results = v
}

func (o ValidationReport) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["passed"] = o.Passed
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *ValidationReport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"passed",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidationReport := _ValidationReport{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidationReport)

	if err != nil {
		return err
	}

	*o = ValidationReport(varValidationReport)

	return err
}

type NullableValidationReport struct {
	value *ValidationReport
	isSet bool
}

func (v NullableValidationReport) Get() *ValidationReport {
	return v.value
}

func (v *NullableValidationReport) Set(val *ValidationReport) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationReport) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationReport(val *ValidationReport) *NullableValidationReport {
	return &NullableValidationReport{value: val, isSet: true}
}

func (v NullableValidationReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


