/*
CE-RISE Hex Core Service API

Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

API version: 0.0.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hexcoresdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryResponse{}

// QueryResponse struct for QueryResponse
type QueryResponse struct {
	Records []Record `json:"records"`
}

type _QueryResponse QueryResponse

// NewQueryResponse instantiates a new QueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryResponse(records []Record) *QueryResponse {
	this := QueryResponse{}
	this.Records = records
	return &this
}

// NewQueryResponseWithDefaults instantiates a new QueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryResponseWithDefaults() *QueryResponse {
	this := QueryResponse{}
	return &this
}

// GetRecords returns the Records field value
func (o *QueryResponse) GetRecords() []Record {
	if o == nil {
		var ret []Record
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
func (o *QueryResponse) GetRecordsOk() ([]Record, bool) {
	if o == nil {
		return nil, false
	}
	return o.Records, true
}

// SetRecords sets field value
func (o *QueryResponse) SetRecords(v []Record) {
	o.Records = v
}

func (o QueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["records"] = o.Records
	return toSerialize, nil
}

func (o *QueryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"records",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryResponse := _QueryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryResponse)

	if err != nil {
		return err
	}

	*o = QueryResponse(varQueryResponse)

	return err
}

type NullableQueryResponse struct {
	value *QueryResponse
	isSet bool
}

func (v NullableQueryResponse) Get() *QueryResponse {
	return v.value
}

func (v *NullableQueryResponse) Set(val *QueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryResponse(val *QueryResponse) *NullableQueryResponse {
	return &NullableQueryResponse{value: val, isSet: true}
}

func (v NullableQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


