/*
CE-RISE Hex Core Service API

Public and admin API for validating, creating, and querying records against versioned CE-RISE model artifacts.

API version: 0.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hexcoresdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelCountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelCountResponse{}

// ModelCountResponse struct for ModelCountResponse
type ModelCountResponse struct {
	// Number of models currently indexed by the registry.
	ModelsCount int64 `json:"models_count"`
}

type _ModelCountResponse ModelCountResponse

// NewModelCountResponse instantiates a new ModelCountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelCountResponse(modelsCount int64) *ModelCountResponse {
	this := ModelCountResponse{}
	this.ModelsCount = modelsCount
	return &this
}

// NewModelCountResponseWithDefaults instantiates a new ModelCountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelCountResponseWithDefaults() *ModelCountResponse {
	this := ModelCountResponse{}
	return &this
}

// GetModelsCount returns the ModelsCount field value
func (o *ModelCountResponse) GetModelsCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ModelsCount
}

// GetModelsCountOk returns a tuple with the ModelsCount field value
// and a boolean to check if the value has been set.
func (o *ModelCountResponse) GetModelsCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelsCount, true
}

// SetModelsCount sets field value
func (o *ModelCountResponse) SetModelsCount(v int64) {
	o.ModelsCount = v
}

func (o ModelCountResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelCountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["models_count"] = o.ModelsCount
	return toSerialize, nil
}

func (o *ModelCountResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"models_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelCountResponse := _ModelCountResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelCountResponse)

	if err != nil {
		return err
	}

	*o = ModelCountResponse(varModelCountResponse)

	return err
}

type NullableModelCountResponse struct {
	value *ModelCountResponse
	isSet bool
}

func (v NullableModelCountResponse) Get() *ModelCountResponse {
	return v.value
}

func (v *NullableModelCountResponse) Set(val *ModelCountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelCountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelCountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelCountResponse(val *ModelCountResponse) *NullableModelCountResponse {
	return &NullableModelCountResponse{value: val, isSet: true}
}

func (v NullableModelCountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelCountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


